[program:laravel-worker]
command=php /var/www/artisan queue:work
directory=/var/www
user=admin
autostart=true
autorestart=true
stopwaitsecs=3600
stdout_logfile=/var/www/storage/logs/laravel-worker.log
stderr_logfile=/var/www/storage/logs/laravel-worker.log

[program:laravel-schedule]
command=php /var/www/artisan schedule:work
directory=/var/www
user=admin
autostart=true
autorestart=true
stopwaitsecs=3600
stdout_logfile=/var/www/storage/logs/laravel-schedule.log
stderr_logfile=/var/www/storage/logs/laravel-schedule.log
