FROM php:8.5-fpm AS base

ARG user=admin
ARG uid=1000

RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    unzip
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip
RUN pecl install redis && docker-php-ext-enable redis
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

FROM base AS supervisor
RUN apt-get update && apt-get install -y supervisor
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /var/log/supervisor /etc/supervisor/conf.d

FROM base AS app
USER $user
